version: 2
jobs:
  testpy27-18:
    docker:
      - image: nousdefions/tox:1.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: 2.7 Tests with Django 1.8 
          command: |
            tox -e py27-18

  testpy27-110:
    docker:
      - image: nousdefions/tox:1.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: 2.7 Tests with Django 1.10 
          command: |
            tox -e py27-110

  testpy27-111:
    docker:
      - image: nousdefions/tox:1.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: 2.7 Tests with Django 1.11 
          command: |
            tox -e py27-111

  testpy34-18:
    docker:
      - image: nousdefions/tox:1.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: 3.4 Tests with Django 1.8 
          command: |
            tox -e py34-18

  testpy34-110:
    docker:
      - image: nousdefions/tox:1.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: 3.4 Tests with Django 1.10 
          command: |
            tox -e py34-110

  testpy34-111:
    docker:
      - image: nousdefions/tox:1.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: 3.4 Tests with Django 1.11 
          command: |
            tox -e py34-111

  testpy35-18:
    docker:
      - image: nousdefions/tox:1.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: 3.5 Tests with Django 1.8 
          command: |
            tox -e py35-18

  testpy35-110:
    docker:
      - image: nousdefions/tox:1.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: 3.5 Tests with Djagno 1.10 
          command: |
            tox -e py35-110

  testpy35-111:
    docker:
      - image: nousdefions/tox:1.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: 3.5 Tests with Django 1.11 
          command: |
            tox -e py35-111

  testpy36-111:
    docker:
      - image: nousdefions/tox:1.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: 3.6 Tests with Djagno 1.11 
          command: |
            tox -e py36-111

workflows:
  version: 2
  test_pys:
    jobs:
      - testpy27-18
      - testpy27-110
      - testpy27-111
      - testpy34-18
      - testpy34-110
      - testpy34-111
      - testpy35-18
      - testpy35-110
      - testpy35-111
      - testpy36-111


#      - run:
#          name: run coveralls
#          command: |
#            . venv/bin/activate
#            coveralls
#
#      - run:
#          name: run report
#          command: |
#            coverage html -d ./test-reports/ 
#
#      - store_artifacts:
#          path: test-reports
#          destination: test-reports
