# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: n42org/tox

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Setup Apt deps 
          command: |
            apt-get update
            apt-get -y install build-essential libssl-dev libffi-dev python-dev libxml2-dev libxmlsec1 xmlsec1 libxmlsec1-openssl-dev libxmlsec1-dev

      - run:
          name: Tox run
          command: |
            tox

      - run:
          name: Setup Virtualenv
          command: |
            pip install virtualenv
            virtualenv venv

      - run:
          name: Setup coverage and coveralls
          command: |
            . venv/bin/activate
            pip install coverage coveralls

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            coverage run setup.py test

      - run:
          name: run coveralls
          command: |
            . venv/bin/activate
            coveralls

      - run:
          name: run report
          command: |
            . venv/bin/activate
            coverage html -d ./test-reports/ 

      - store_artifacts:
          path: test-reports
          destination: test-reports
